### ISSUE TITLE
Does Wizzilla mean anything to you?

### ISSUE THREAD

**Issue by 007revad** [mgreen27/DetectRaptor#51]
Hi Matt,

Over a decade ago a Matt Green and myself created an app named Wizzilla. I was just wondering if you're the same Matt Green?

I noticed your name on the aussie GitHub top committers list. https://committers.top/australia#mgreen27

**Comment by mgreen27** [comment]
Hi @007revad not a project I have been involved in. One of the downsides to having a relatively common name :)
