### ISSUE TITLE
Windows.Detection.MFT - regex error

### ISSUE THREAD

**Issue by ibyf0r3ns1cs** [mgreen27/DetectRaptor#58]
Just a heads-up, the latest version of the MFT includes all new RMMS, and one of the lines had a regex issue:

Before:
RMM - FleetDeck,^fleetdeck_agent_svc.\exe$,.,,FleetDeck - fleetdeck.io,Medium

After fixing:
RMM - FleetDeck,^fleetdeck_agent_svc.exe$,.,,FleetDeck - fleetdeck.io,Medium

I've corrected the escape character before the ".exe" part."

**Comment by mgreen27** [comment]
thank you for that!

Just updated the csv and confimed this vql should be good now
