### ISSUE TITLE
Missing YARA rules

### ISSUE THREAD

**Issue by ruppde** [mgreen27/DetectRaptor#65]
hi Matthew,

the internet is complaing, that DetectRaptor doesn't find enough webshells:

https://x.com/malmoeb/status/1802617141847576641

The easiest fix would to be just add these YARA rules, which find all 4 webshells: https://github.com/Neo23x0/signature-base/blob/master/yara/gen_webshells.yar

The complete fix would to include the extended rule package of https://github.com/YARAHQ/yara-forge (contains the rules above and much more)

best regards
arnim

**Comment by mgreen27-r7** [comment]
hey - thanks for that - ill update.

One of the issues in VR is some of the Yara modules were previously not supported so automation is difficult and I havent looked at these rules for almost a year. Its probably a good use case for yaraforge!

**Comment by mgreen27-r7** [comment]
Ok I have updated to use any yara rules in the Full Yara-Forge set with the string "webshell" in the name or description.

Should enable this rule to be continuously updated with webshell content

**Comment by Neo23x0** [comment]
Great work
