### ISSUE TITLE
Wrong/missing yara file url

### ISSUE THREAD

**Issue by zmlilo** [mgreen27/DetectRaptor#69]
Hi

When i tried to run **DetectRaptor.Generic.Detection.YaraFile** artifact i get the following error(s)

_Checking FileYaraLinux: Unable to download file from https://github.com/mgreen27/DetectRaptor/raw/master/yara/full_linux_file.yarc.gz: 404 Not Found_

This path specified here:
https://github.com/mgreen27/DetectRaptor/blob/26c17a633e49fe7ac2b688b72a075be9d6993b41/vql/YaraFile.yaml#L38

And similar for windows too.

I used the **Exchange.Server.Import.DetectRaptor** for installing DetectRaptor ...

Velociraptor version: `"version":"0.72-rc1"`

**Comment by mgreen27** [comment]
Looks like I inadvertently removed these yesterday when I ran an update - sorry about that. They generate each Sunday so were not recreated. I just readded so it should be working now.

Thank you for reporting!

**Comment by mgreen27** [comment]
I tested and it works. Please make sure to reimport the DetectRaptor rules.
![image](https://github.com/mgreen27/DetectRaptor/assets/13081800/3fa60a48-f42f-42f7-a4e5-c5ce3364ae1a)
