### ISSUE TITLE
additional indicators

### ISSUE THREAD

**Issue by 0x90v1** [mgreen27/DetectRaptor#8]
Hey Matthew

Could you add the following indicators to the csv list:

MFT:
 - action1: RMM
 - dbeaver: Enumeration

best regards Andreas (InfoGuard)

**Comment by mgreen27** [comment]
Hi @0x90v1,

Thank you for creating the request - I would be happy to!

Just let me know what fields you would like to add to for your keywords, filename or pathname? (im assuming PathName)
The available fields are: `Detection | Filename | PathName | Reference`

Alternatively, if you prefer feel free to just edit the file in Github and submit a PR and I can approve.

Matt

**Comment by 0x90v1** [comment]
oh cool yeah sure I'm going that way and editing it directly than :-)
